config/routes.rb
StudentBodyRails::Application.routes.draw do
  resources :students
  root :to => 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentBodyRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Flatiron School - Students</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag :application %>
</head>

<body>
<div id="page">
  <header id="header">
    <div class="center">
      <nav id="main-menu">
        <ul>
          <li class="site-title"><a href="index.html">Students @ Flatiron School</a></li>
        </ul>
        <ul>
          <li><a href="http://flatironschool.com">More about Our School</a></li>
        </ul>
      </nav>
      <div class="clear"></div>
    </div>
  </header>

  <section id="about" class="about-us content">
    <div class="center">
      <h1 id="intro" style="padding-top: 20px">
        Every story has heroes. We're 20 people on a journey to learn to love code.
      </h1>
      <!-- <h2 class="title"><span>The Heroes</span></h2> -->
      <div class="columns">

        <% @students.each_with_index do |student, index|  %>

        <div class="one_third <%= "last" if (index + 1) % 3 == 0 %>">
          <%= link_to( image_tag(student.image_url.gsub('images/', ''), :class => 'person'), student_path(student) ) %>
            <div class="name-position">
              <h2><%= link_to("#{student.first_name} #{student.last_name}", student_path(student)) %></h2>
              <div class="position"><%= student.tagline2 %></div>
            </div>
            <div class="clear"></div>
          </a>
          <p class="excerpt"><%= student.excerpt %></p>
        </div>

        <% end %>



        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
    <!-- /END .center-->
  </section>
  <!-- /END #about-us -->


   <section id="copyright" class="footer content">
    <div class="center">
      <p>&copy; 2012. All Your Rights Are Belong To Us.</p>
      <div class="clear"></div>
    </div>
  </section>
</div>


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33578770-1']);
  _gaq.push(['_setDomainName', 'flatironschool.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!--/border-->
<div id="left-border"></div>
<div id="right-border"></div>
<div id="top-border"></div>
<div id="bottom-border"></div>
</body>
</html>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Flatiron School - Students</title>
  <%= stylesheet_link_tag "application" %>
  <script id="twitter-wjs" src="http://platform.twitter.com/widgets.js"></script>
  <%= javascript_include_tag :application %>
</head>

<body>
<div id="page">
  <header id="header">
    <div class="center">
      <nav id="main-menu">
        <ul>
          <li class="site-title"><a href="index.html">Students @ Flatiron School</a></li>
        </ul>
        <ul>
          <li><a href="http://flatironschool.com">More about Our School</a></li>
        </ul>
      </nav>
      <div class="clear"></div>
    </div>
  </header>

  <section id="about" class="about-us content">


      <div class="jrcolumns">
          <!-- LEFT COLUMN -->
          <div id='navcontainer'class="one_third">




<div class=<%= @student.image_class %>>
  <%= image_tag  'circle-mask.png' %>
</div>


<nav id='side-nav'>
              <ul>
                <li class='mail'><a href="mailto:<%= @student.email %>">Mail</a></li>
                <li class='blog'><a href=<%= @student.blog %>>Blog</a></li>
                <li class='linkedin'><a href=<%= @student.linked_in %>>LinkedIn</a></li>
                <li class='twitter'><a href=<%= @student.twitter %>>Twitter</a></li>
              </ul>
            </nav> <!-- this is the end of side nav -->
          </div>
          <!-- MIDDLE COLUMN -->
          <div class="two_third">
            <h1><%= @student.first_name + " " + @student.last_name %></h1>
            <h2 id='tagline'><%= @student.tag_line %></h2>
            <p><%= @student.bio %></p>

<br/><br/>
            <h2 id='tagline'>My favorite apps</h2>

<div class="one_third">
<h4><%= @student.app_1 %></h4>
<p><%= @student.app_1_desc %></p>
</div>


<div class="one_third">
<h4><%= @student.app_2 %></h4>
<p><%= @student.app_2_desc %></p>
</div>

<div class="one_third last">
<h4><%= @student.app_3 %></h4>
<p><%= @student.app_3_desc %></p>
</div>


          </div>
<!-- RIGHT COLUMN -->

        <div class="clear"></div>

        <h2 class="title"><span>Coder Cred</span></h2>



          <div class="columns">
          <div class="coder-cred">

            <div class="one_fifth"><a href=<%= @student.github %>><div class="cred-github"></div></a></div>
            <div class="one_fifth"><a href=<%= @student.code_school %>><div class="cred-codeschool"></div></a></div>
            <div class="one_fifth"><a href=<%= @student.coder_wall %>><div class="cred-coderwall"></div></a></div>
            <div class="one_fifth"><a href=<%= @student.stack_overflow %>><div class="cred-stackoverflow"></div></a></div>
            <div class="one_fifth last"><a href=<%= @student.treehouse %>><div class="cred-treehouse"></div></a></div>

          </div>
          </div>


        <div class="clear"></div>
        <h2 class="title"><span>Social Nerdery</span></h2>


        <div class="one_half">

          <%= @student.githubfeed.html_safe %>

        </div>
        <div class="one_half last">


            <%= @student.twitterfeed.html_safe %>


        </div>
      <div class="clear"></div>
        <h2 class="title">&nbsp;</h2>
<section id="copyright" class="footer content">
    <div class="center">
      <p>&copy; 2012. All Your Rights Are Belong To Us.</p>
      <div class="clear"></div>
    </div>
  </section>


        </div>
    </div>
  </section>
</body>
</html>